version: '3.3'

services:
  webserver:
    hostname: webserver
    build:
      context: ./_dummyWebserver
      dockerfile: Dockerfile
    image: traefikauthtest/webserver:latest
    labels:
      - "traefik.frontend.rule=Host:cyphernode.docker.localhost"
      - "traefik.frontend.rule=PathPrefixStrip:/dummy"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.frontend.auth.forward.address=http://192.168.178.90:3032/forwardauth"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Auth-User-Claims"
#      - "traefik.frontend.auth.forward.trustForwardHeader=true"
    restart: always
  cyphernodeadmin:
    hostname: cyphernodeadmin
    build:
      context: ./
      dockerfile: Dockerfile

    image: traefikauthtest/cyphernodeadmin:latest
    labels:
      - "traefik.frontend.rule=Host:cyphernode.docker.localhost"
      - "traefik.frontend.rule=PathPrefixStrip:/admin"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.enable=true"
      - "traefik.port=3030"
      - "traefik.frontend.auth.forward.address=http://192.168.178.90:3032/forwardauth"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Auth-User-Claims"
    #      - "traefik.frontend.auth.forward.trustForwardHeader=true"
    restart: always
    volumes:
      - "/Users/jash/go/src/github.com/SatoshiPortal/cam/apps:/data/apps"
  traefik:
    hostname: traefik
    image: traefik:1.7
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
#      - "--logLevel=DEBUG"
#      - "--debug"
      - "--docker"
