version: '3.3'

services:
  db:
    hostname: db
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=cnadmin
      - POSTGRES_PASSWORD=cnadmin
      - POSTGRES_DB=cnadmin
    ports:
      - 5432:5432
